# Generated by Django 4.2.3 on 2025-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdetail',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
