# Generated by Django 4.2.3 on 2025-03-12 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_getintouch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='phone_number',
            field=models.CharField(help_text='for example: +998 __ ___ __ __', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998 __ ___ __ __'. Up to 13 digits allowed.", regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')]),
        ),
    ]
