# Generated by Django 5.1.1 on 2024-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_image_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
