# Generated by Django 5.1.1 on 2024-10-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_blog_tags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at', 'is_published'], name='blog_blog_created_3a33de_idx'),
        ),
    ]
