# Generated by Django 5.1.1 on 2024-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_blog_blog_created_3a33de_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
